name: 'Sync GitHub Repos To Gitee Bot'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Sync (attempt 1/3)'
        id: sync_attempt_1
        continue-on-error: true
        uses: lueyoung/hub-mirror-action@master
        with:
          src: github/lueyoung
          dst: gitee/lueyoung
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "practice-exercises"
          account_type: user
          clone_style: "https"
          force_update: true
          debug: true
          timeout: '1h'
      - name: 'Wait before sync retry 2/3'
        if: ${{ steps.sync_attempt_1.outcome == 'failure' }}
        run: sleep 30
      - name: 'Sync (attempt 2/3)'
        id: sync_attempt_2
        if: ${{ steps.sync_attempt_1.outcome == 'failure' }}
        continue-on-error: true
        uses: lueyoung/hub-mirror-action@master
        with:
          src: github/lueyoung
          dst: gitee/lueyoung
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "practice-exercises"
          account_type: user
          clone_style: "https"
          force_update: true
          debug: true
          timeout: '1h'
      - name: 'Wait before sync retry 3/3'
        if: ${{ steps.sync_attempt_2.outcome == 'failure' }}
        run: sleep 60
      - name: 'Sync (attempt 3/3)'
        if: ${{ steps.sync_attempt_2.outcome == 'failure' }}
        uses: lueyoung/hub-mirror-action@master
        with:
          src: github/lueyoung
          dst: gitee/lueyoung
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "practice-exercises"
          account_type: user
          clone_style: "https"
          force_update: true
          debug: true
          timeout: '1h'
